build(ci): add run_compose for docker compose builds

diff --git a/.github/workflows/staging-deploy.yml b/.github/workflows/staging-deploy.yml
--- a/.github/workflows/staging-deploy.yml
+++ b/.github/workflows/staging-deploy.yml
@@ -1,27 +1,27 @@
-name: 🚀 Deploy SMSWithoutBorders Blog on Server (staging)
+name: Deploy SMSWithoutBorders Blog on Server (staging)
 on:
   push:
     branches:
       - staging
 jobs:
   deploy:
-    name: 🚀 Execute Deployment Script on Server
+    name: Execute Deployment Script on Server
     runs-on: ubuntu-latest
     environment:
       name: staging
       url: https://staging.smswithoutborders.com:18000
     steps:
-      - name: 🚀 Execute Remote SSH Commands
+      - name: Execute Remote SSH Commands
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.PASSWORD }}
+          key: ${{ secrets.KEY }}
           script: |
             set -e
 
             echo "============================"
-            echo "🚀 Updating repository ..."
+            echo "Updating repository ..."
             echo "============================"
             cd ${{ secrets.PROJECT_PATH }}
             if ! git pull; then
@@ -33,7 +33,7 @@ jobs:
             echo "==============================="
 
             echo "========================="
-            echo "🚀 Building project ..."
+            echo "Building project ..."
             echo "========================="
             if ! ${{ secrets.BUILD_CMD }}; then
               echo "❌ Error building project!"
@@ -42,4 +42,10 @@ jobs:
             echo "==========================="
             echo "✅ Project build complete"
             echo "==========================="
-            
+            if ! ${{ secrets.CLEANUP_CMD }}; then
+              echo "❌ Error cleaning up builds!"
+              exit 1
+            fi
+            echo "============================="
+            echo "✅ Cleanup complete"
+            echo "============================="
